In [2]:
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist



KNN

In [29]:
def eculadine(vec1, vec2):
    reVec = np.empty((0, 2))
    i=0
    while(i<int(len(vec1))):
        reVec = np.append(reVec, np.sqrt(np.add(np.square(np.subtract(vec1[i],vec2[i])), np.square((np.subtract(vec1[i+1],vec2[i+1]))))))

        #reVec = np.append(reVec, np.sqrt(np.add(np.square((vec1[i]-vec2[i])), np.square((vec1[i+1]-vec2[i+1])))))  
        i+=2
    return reVec

In [30]:
def get_neighbors(train_set, Y_train, test_row, K_Nearest):
    distances = list()
    for i in range (len(train_set)):
        #print()
        dis = eculadine(train_set[i], test_row)
        dis= np.sum(dis)
        distances.append((Y_train[i], dis))
        #print(dis)
    #print(distances)
    distances.sort(key=lambda tup: tup[1])

    neighbors = list()
    #print(distances)
    for i in range(K_Nearest):
        neighbors.append(distances[i][0])
    return neighbors

In [5]:
def voting(neighbors):
    return max(neighbors,key=neighbors.count)

Stanalone Functions

In [6]:
def Loss(Y, Y_predicted):
    return(sum(np.square(Y - Y_predicted))/Y.size)

def Normalize(X):
    return((X-X.min())/(X.max()-X.min()))

def Binarize(X):
    X [X < 200] = 0
    X [X >= 200] = 1       
    return X


Image Processing Functions

In [7]:
def centroid(X):
    colSum=X.sum(axis=0)
    M00=np.sum(colSum)
    M10 =np.array([])
    M01 =np.array([])
    for i in range(7):
        M10= np.append(M10, (colSum[i]*i))
        
    for i in range(14):
       M01 = np.append(M01,(colSum[i]*i))
    M10 = np.sum(M10)
    M01 = np.sum(M01)
    if(M00==0):
        Xc= 0
        Yc= 0
    else:
        Xc = M10/M00
        Yc = M01/M00
    
    return np.array([Xc, Yc])


In [8]:
def FeatureImage(X):
    vector=np.array([])
    for i in range(2):
        for j in range(4):
            vector= np.append(vector, centroid(X[j*7:((j+1)*7) ,i*14:((i+1)*14)]))
    return vector

In [9]:
def plot_digit(X, y, idx):
    plt.imshow(X[idx], cmap='Greys', interpolation='nearest')
    plt.title('true label: %d' % y[idx])
    plt.show()

Program 

In [10]:
(train_X, train_y), (test_X, test_y) = mnist.load_data()
train_X.shape

(60000, 28, 28)

In [11]:
train_X =Binarize(train_X)
train_X[0]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 

In [12]:
vec = np.array([])
for i in range(60000):
    vec = np.append(vec, FeatureImage(train_X[i]))
vec.shape

(960000,)

In [13]:
vec =vec.reshape(60000, 16)
vec.shape

(60000, 16)

In [27]:
vec[0]

array([ 0.        , 13.        ,  0.        , 11.15789474,  0.        ,
       12.5       ,  0.89473684,  9.10526316,  1.77777778,  4.22222222,
        1.57142857,  1.57142857,  2.5       ,  2.5       ,  0.        ,
        0.        ])

In [21]:
test_X =Binarize(test_X)


In [25]:
test_X[0]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 

In [22]:
vecTest = np.array([])
for i in range(10000):
    vecTest = np.append(vecTest, FeatureImage(test_X[i]))
print(vecTest.shape)
vecTest =vecTest.reshape(10000, 16)
print(vecTest.shape)



(160000,)
(10000, 16)


In [26]:
vecTest[0]

array([ 0.        ,  0.        ,  0.66666667,  9.66666667,  0.        ,
       13.        ,  0.        , 12.15384615,  0.        ,  0.        ,
        4.06666667,  4.06666667,  1.83333333,  1.83333333,  0.        ,
        0.        ])

In [28]:
vec[1]

array([ 0.        ,  0.        ,  0.        , 11.        ,  0.        ,
        7.5       ,  0.        , 10.1875    ,  2.75      ,  2.75      ,
        2.90909091,  4.18181818,  3.15384615,  4.23076923,  0.        ,
        0.        ])

In [15]:
# print(Loss(vec[10], vec[1]))
# print(Loss(vec[0], vec[1]))
# print(Loss(vec[10], vec[2000]))
# print(Loss(vec[2002], vec[2000]))
# print(train_y[10])
# print(train_y[1])
# print(train_y[2000])
# print(train_y[2002])
# print(train_y[0])


In [16]:
# print(Loss(vec[5050], vec[2002]))


In [17]:
# plot_digit(train_X, train_y, 0) 
# plot_digit(train_X, train_y, 3000) 
# plot_digit(train_X, train_y, 1) 
# plot_digit(train_X, train_y, 5050 )


In [24]:
vecTest[0]

array([ 0.        ,  0.        ,  0.66666667,  9.66666667,  0.        ,
       13.        ,  0.        , 12.15384615,  0.        ,  0.        ,
        4.06666667,  4.06666667,  1.83333333,  1.83333333,  0.        ,
        0.        ])

In [39]:
print(test_y[90])


3


In [41]:
print(voting(get_neighbors(vec, train_y, vecTest[90], 3)))

3
