In [1]:
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist



KNN

In [2]:
def eculadine(vec1, vec2):
    reVec = np.empty((0, 2))
    i=0
    while(i<int(len(vec1))):
        reVec = np.append(reVec, np.sqrt(np.add(np.square(np.subtract(vec1[i],vec2[i])), np.square((np.subtract(vec1[i+1],vec2[i+1]))))))

        #reVec = np.append(reVec, np.sqrt(np.add(np.square((vec1[i]-vec2[i])), np.square((vec1[i+1]-vec2[i+1])))))  
        i+=2
    return reVec

In [3]:
def get_neighbors(train_set, Y_train, test_row, K_Nearest):
    distances = list()
    for i in range (len(train_set)):
        #print()
        dis = eculadine(train_set[i], test_row)
        dis= np.sum(dis)
        distances.append((Y_train[i], dis))
        #print(dis)
    #print(distances)
    distances.sort(key=lambda tup: tup[1])

    neighbors = list()
    #print(distances)
    for i in range(K_Nearest):
        neighbors.append(distances[i][0])
    return neighbors

In [4]:
def voting(neighbors):
    return max(neighbors,key=neighbors.count)

Stanalone Functions

In [1]:
def Loss(Y, Y_predicted):
    return(sum(np.square(Y - Y_predicted))/Y.size)

def Normalize(X):
    return((X-X.min())/(X.max()-X.min()))

def Binarize(X):
    X [X < 200] = 0
    X [X >= 200] = 1       
    return X

def calculate_accuracy(predicted_y, y):
    guessWrong = 0
    if(len(predicted_y) == len(y)):
        ind = 0
        for i in predicted_y:
            if(i != y[ind]):
                guessWrong = guessWrong + 1
            ind+=1
        acc = ( (len(predicted_y)- guessWrong) / len(predicted_y))
        return acc
    return 0



Image Processing Functions

In [6]:
def centroid(X):
    colSum=X.sum(axis=0)
    M00=np.sum(colSum)
    M10 =np.array([])
    M01 =np.array([])
    for i in range(7):
        M10= np.append(M10, (colSum[i]*i))
        
    for i in range(14):
       M01 = np.append(M01,(colSum[i]*i))
    M10 = np.sum(M10)
    M01 = np.sum(M01)
    if(M00==0):
        Xc= 0
        Yc= 0
    else:
        Xc = M10/M00
        Yc = M01/M00
    
    return np.array([Xc, Yc])


In [7]:
def FeatureImage(X):
    vector=np.array([])
    for i in range(2):
        for j in range(4):
            vector= np.append(vector, centroid(X[j*7:((j+1)*7) ,i*14:((i+1)*14)]))
    return vector

In [8]:
def plot_digit(X, y, idx):
    plt.imshow(X[idx], cmap='Greys', interpolation='nearest')
    plt.title('true label: %d' % y[idx])
    plt.show()

Program 

In [9]:
(train_X, train_y), (test_X, test_y) = mnist.load_data()
train_X.shape

(60000, 28, 28)

In [10]:
train_X =Binarize(train_X)
train_X[0]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 

In [11]:
vec = np.array([])
for i in range(60000):
    vec = np.append(vec, FeatureImage(train_X[i]))
vec.shape

(960000,)

In [12]:
vec =vec.reshape(60000, 16)
vec.shape

(60000, 16)

In [13]:
vec[0]

array([ 0.        , 13.        ,  0.        , 11.15789474,  0.        ,
       12.5       ,  0.89473684,  9.10526316,  1.77777778,  4.22222222,
        1.57142857,  1.57142857,  2.5       ,  2.5       ,  0.        ,
        0.        ])

In [14]:
test_X =Binarize(test_X)


In [15]:
vecTest = np.array([])
for i in range(10000):
    vecTest = np.append(vecTest, FeatureImage(test_X[i]))
print(vecTest.shape)
vecTest =vecTest.reshape(10000, 16)
print(vecTest.shape)



(160000,)
(10000, 16)


In [16]:
print(test_y[90])


3


In [17]:
print(voting(get_neighbors(vec, train_y, vecTest[90], 3)))

3


In [22]:
predicted_y = np.array([])
predicted_y = np.append(predicted_y, voting(get_neighbors(vec, train_y, vecTest[0], 3)))


In [24]:
test_y[:100]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6,
       6, 5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2,
       3, 5, 1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4,
       6, 4, 3, 0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3,
       6, 1, 3, 6, 9, 3, 1, 4, 1, 7, 6, 9], dtype=uint8)

In [25]:
predicted_y = np.array([])
for i  in range(100):
    predicted_y = np.append(predicted_y, voting(get_neighbors(vec, train_y, vecTest[i], 3)))

calculate_accuracy (predicted_y, test_y[:100])

0.87

In [27]:
pre = np.array([])
for i  in range(1000):
    pre = np.append(pre, voting(get_neighbors(vec, train_y, vecTest[i], 3)))

calculate_accuracy (pre, test_y[:1000])

0.801