In [1]:
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist
import math
from sklearn.neighbors import KNeighborsClassifier

In [2]:
def Loss(Y, Y_predicted):
    return(sum(np.square(Y - Y_predicted))/Y.size)

def Normalize(X):
    return((X-X.min())/(X.max()-X.min()))

def Binarize(X):
    X [X < 150] = 0
    X [X >= 150] = 1       
    return X

def calculate_accuracy(predicted_y, y):
    guessWrong = 0
    if(len(predicted_y) == len(y)):
        ind = 0
        for i in predicted_y:
            if(i != y[ind]):
                guessWrong = guessWrong + 1
            ind+=1
        acc = ( (len(predicted_y)- guessWrong) / len(predicted_y))
        return (acc*100)
    return 0

In [3]:
def centroid(X):
    M00=np.sum(X.sum(axis=1))
    M10 =np.array([])
    M01 =np.array([])
    for i in range(X.shape[0]):
        M10= np.append(M10, (X[i].sum(axis=0)*(i+1)))
        
    for i in range(X.shape[1]):
        M01 = np.append(M01,(X[:,i].sum(axis=0)*(i+1)))
    M10 = np.sum(M10)
    M01 = np.sum(M01)
    if(M00==0):
        Xc= 0
        Yc= 0
    else:
        Xc = M10/M00
        Yc = M01/M00
    return np.array([Xc, Yc])

In [4]:
centroid(np.array([[0, 0, 0, 0], [ 0, 1, 1 , 0], [0, 1, 2, 0], [1,0,0,0]]))

array([2.83333333, 2.33333333])

In [5]:
def FeatureImage(X):
    vector=np.array([])
    for i in range(2):
        for j in range(4):              #0-7, 0--14
            vector= np.append(vector, centroid(X[j*7:((j+1)*7) ,i*14:((i+1)*14)]))
    return vector

In [6]:
(train_X, train_y), (test_X, test_y) = mnist.load_data()
train_X.shape

(60000, 28, 28)

In [7]:
train_X =Binarize(train_X)
train_X[0]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 

In [8]:
test_X = Binarize(test_X)

In [9]:
test_X[1]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 

In [10]:
vec = np.array([])
for i in range(60000):
    vec = np.append(vec, FeatureImage(train_X[i]))
vec.shape

In [ ]:
vec =vec.reshape(60000, 16)
vec.shape

(60000, 16)

In [ ]:
vec[0]

array([ 7.        , 14.        ,  2.57894737, 12.15789474,  7.        ,
       13.5       ,  2.52631579, 10.10526316,  6.77777778,  5.22222222,
        2.14285714,  2.57142857,  4.45454545,  3.5       ,  1.        ,
        1.        ])

In [ ]:
# test_X =Binarize(test_X)


In [ ]:
vecTest = np.array([])
for i in range(10000):
    vecTest = np.append(vecTest, FeatureImage(test_X[i]))
print(vecTest.shape)
vecTest =vecTest.reshape(10000, 16)
print(vecTest.shape)


(160000,)
(10000, 16)


In [ ]:
ImagClass = KNeighborsClassifier()
ImagClass.fit(vec , train_y)

KNeighborsClassifier()

In [ ]:
vecTest[1].shape

(16,)

In [ ]:
print(ImagClass.predict(vecTest[1].reshape(1, -1)))

[2]


In [ ]:
print(test_y[1])

2


In [ ]:
pre3 = np.array([])
pre5 = np.array([])
for i  in range(10000):
    pre3 = np.append(pre3, ImagClass.predict(vecTest[i].reshape(1, -1)))

calculate_accuracy (pre3, test_y[:10000])


91.74